server:
  port: 5005
spring:
  application:
    name: movement-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movementBank