server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: paymenttype
          uri: https://github.com/RECAVERO/consolidado/
          search-paths: config-data
  application:
    name: config-service

